CREATE TABLE SPACES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SPACE_NUM INT NOT NULL,
	REGION_NUM INT NOT NULL,
	FREE BOOLEAN NOT NULL,
	STAMP DATETIME
);

CREATE TABLE SPACES_UPDATE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SPACE_NUM INT NOT NULL,
	REGION_NUM INT NOT NULL,
	FREE BOOLEAN NOT NULL,
	STAMP DATETIME
);

CREATE UNIQUE INDEX SPACES_UPDATE_INDEX
ON SPACES_UPDATE(SPACE_NUM, REGION_NUM);
